2021-05-09 01:36:35,698 INFO    MainThread:26061 [wandb_setup.py:_flush():69] setting env: {}
2021-05-09 01:36:35,699 INFO    MainThread:26061 [wandb_init.py:_log_setup():336] Logging user logs to /home/trenton-windows/repos/spicy-dann/wandb/offline-run-20210509_013635-1nvc08wh/logs/debug.log
2021-05-09 01:36:35,699 INFO    MainThread:26061 [wandb_init.py:_log_setup():337] Logging internal logs to /home/trenton-windows/repos/spicy-dann/wandb/offline-run-20210509_013635-1nvc08wh/logs/debug-internal.log
2021-05-09 01:36:35,699 INFO    MainThread:26061 [wandb_init.py:init():369] calling init triggers
2021-05-09 01:36:35,699 INFO    MainThread:26061 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-09 01:36:35,699 INFO    MainThread:26061 [wandb_init.py:init():418] starting backend
2021-05-09 01:36:35,700 INFO    MainThread:26061 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-09 01:36:35,712 INFO    MainThread:26061 [backend.py:ensure_launched():132] starting backend process...
2021-05-09 01:36:35,718 INFO    MainThread:26061 [backend.py:ensure_launched():137] started backend process with pid: 26081
2021-05-09 01:36:35,723 INFO    MainThread:26061 [wandb_init.py:init():423] backend started and connected
2021-05-09 01:36:35,725 INFO    MainThread:26061 [wandb_init.py:init():465] updated telemetry
2021-05-09 01:36:35,733 INFO    MainThread:26061 [wandb_init.py:init():522] starting run threads in backend
2021-05-09 01:36:39,080 INFO    MainThread:26061 [wandb_run.py:_console_start():1565] atexit reg
2021-05-09 01:36:39,081 INFO    MainThread:26061 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-09 01:36:39,081 INFO    MainThread:26061 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-09 01:36:39,085 INFO    MainThread:26061 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-09 01:36:39,085 INFO    MainThread:26061 [wandb_init.py:init():546] run started, returning control to user process
2021-05-09 01:36:39,086 INFO    MainThread:26061 [wandb_run.py:_config_callback():787] config_cb None None {'dataset': 'camelyon17', 'data_root': './WILDS', 'model_name': 'resnet18', 'batch_size': 3, 'n_epochs': 1, 'get_train_metrics': True, 'save_every': 5, 'run_name': 'dev-small', 'max_val_batches': 2}
2021-05-09 01:38:52,117 INFO    MainThread:26061 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 1
2021-05-09 01:38:52,136 INFO    MainThread:26061 [wandb_run.py:_restore():1507] restore
