2021-05-09 01:25:14,302 INFO    MainThread:25173 [internal.py:wandb_internal():91] W&B internal server running at pid: 25173, started at: 2021-05-09 01:25:14.302193
2021-05-09 01:25:14,308 DEBUG   HandlerThread:25173 [handler.py:handle_request():121] handle_request: run_start
2021-05-09 01:25:14,308 INFO    WriterThread:25173 [datastore.py:open_for_write():77] open: /home/trenton-windows/repos/spicy-dann/wandb/offline-run-20210509_012513-wx16txm9/run-wx16txm9.wandb
2021-05-09 01:25:14,352 DEBUG   HandlerThread:25173 [meta.py:__init__():39] meta init
2021-05-09 01:25:14,352 DEBUG   HandlerThread:25173 [meta.py:__init__():53] meta init done
2021-05-09 01:25:14,353 DEBUG   HandlerThread:25173 [meta.py:probe():210] probe
2021-05-09 01:25:14,355 DEBUG   HandlerThread:25173 [meta.py:_setup_git():200] setup git
2021-05-09 01:25:14,367 DEBUG   HandlerThread:25173 [meta.py:_setup_git():207] setup git done
2021-05-09 01:25:14,367 DEBUG   HandlerThread:25173 [meta.py:_save_pip():57] save pip
2021-05-09 01:25:14,368 DEBUG   HandlerThread:25173 [meta.py:_save_pip():71] save pip done
2021-05-09 01:25:14,368 DEBUG   HandlerThread:25173 [meta.py:_save_conda():78] save conda
2021-05-09 01:25:16,921 DEBUG   HandlerThread:25173 [meta.py:_save_conda():86] save conda done
2021-05-09 01:25:16,921 DEBUG   HandlerThread:25173 [meta.py:probe():252] probe done
2021-05-09 01:27:31,589 WARNING MainThread:25173 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-05-09 01:27:31,878 WARNING MainThread:25173 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-05-09 01:27:31,878 ERROR   MainThread:25173 [internal.py:wandb_internal():150] Internal process interrupted.
2021-05-09 01:27:32,333 INFO    SenderThread:25173 [sender.py:finish():925] shutting down sender
2021-05-09 01:27:32,639 INFO    WriterThread:25173 [datastore.py:close():258] close: /home/trenton-windows/repos/spicy-dann/wandb/offline-run-20210509_012513-wx16txm9/run-wx16txm9.wandb
2021-05-09 01:27:32,656 INFO    HandlerThread:25173 [handler.py:finish():632] shutting down handler
2021-05-09 01:27:32,657 INFO    MainThread:25173 [internal.py:handle_exit():78] Internal process exited
