2021-05-09 01:23:07,051 INFO    MainThread:24974 [internal.py:wandb_internal():91] W&B internal server running at pid: 24974, started at: 2021-05-09 01:23:07.050515
2021-05-09 01:23:07,056 INFO    WriterThread:24974 [datastore.py:open_for_write():77] open: /home/trenton-windows/repos/spicy-dann/wandb/offline-run-20210509_012306-2ngcimvh/run-2ngcimvh.wandb
2021-05-09 01:23:07,056 DEBUG   HandlerThread:24974 [handler.py:handle_request():121] handle_request: run_start
2021-05-09 01:23:07,096 DEBUG   HandlerThread:24974 [meta.py:__init__():39] meta init
2021-05-09 01:23:07,098 DEBUG   HandlerThread:24974 [meta.py:__init__():53] meta init done
2021-05-09 01:23:07,099 DEBUG   HandlerThread:24974 [meta.py:probe():210] probe
2021-05-09 01:23:07,100 DEBUG   HandlerThread:24974 [meta.py:_setup_git():200] setup git
2021-05-09 01:23:07,113 DEBUG   HandlerThread:24974 [meta.py:_setup_git():207] setup git done
2021-05-09 01:23:07,114 DEBUG   HandlerThread:24974 [meta.py:_save_pip():57] save pip
2021-05-09 01:23:07,114 DEBUG   HandlerThread:24974 [meta.py:_save_pip():71] save pip done
2021-05-09 01:23:07,114 DEBUG   HandlerThread:24974 [meta.py:_save_conda():78] save conda
2021-05-09 01:23:09,727 DEBUG   HandlerThread:24974 [meta.py:_save_conda():86] save conda done
2021-05-09 01:23:09,727 DEBUG   HandlerThread:24974 [meta.py:probe():252] probe done
2021-05-09 01:25:03,417 WARNING MainThread:24974 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-05-09 01:25:03,587 WARNING MainThread:24974 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-05-09 01:25:03,587 ERROR   MainThread:24974 [internal.py:wandb_internal():150] Internal process interrupted.
2021-05-09 01:25:04,079 INFO    SenderThread:24974 [sender.py:finish():925] shutting down sender
2021-05-09 01:25:04,345 INFO    WriterThread:24974 [datastore.py:close():258] close: /home/trenton-windows/repos/spicy-dann/wandb/offline-run-20210509_012306-2ngcimvh/run-2ngcimvh.wandb
2021-05-09 01:25:04,369 INFO    HandlerThread:24974 [handler.py:finish():632] shutting down handler
2021-05-09 01:25:04,373 INFO    MainThread:24974 [internal.py:handle_exit():78] Internal process exited
